unbind C-b
set -g prefix C-Space
bind -n C-Space send-prefix

# Start windows and panes at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Scroll with mouse.
setw -g mouse on

setw -g history-limit 999999

# Create a new window from the current path, not from $HOME.
bind c new-window -c "#{pane_current_path}"
bind & select-window -t 1
bind é select-window -t 2
bind \" select-window -t 3
bind \' select-window -t 4
bind \( select-window -t 5
